services:
  app:
    image: ghcr.io/shba007/portfolio-monalisa:latest@sha256:f726fb4771367c7555c606f2653db8261e02652239221ac26650da13657f9ae1
    env_file:
      - .env
    volumes:
      - portfolio-monalisa_static:/app/static
      - portfolio-monalisa_data:/app/.data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  portfolio-monalisa_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-monalisa/static
  portfolio-monalisa_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-monalisa/.data

networks:
  internal:
    driver: overlay
